name: flutter_unit
description: A new Flutter application.
publish_to: none
version: 3.0.0
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4


  flutter_bloc: ^8.1.6 # 状态管理
  equatable: ^2.0.5 # 相等辅助
  stream_transform: ^2.1.0

  ## fx 架构 - app 启动器
  fx_boot_starter: 0.0.1
  fx_app_env:
    path: modules/fx_app_env

  ## tolyui
  tolyui: ^0.0.2+15


  package_info_plus: ^8.0.0 # 应用包信息
  r_upgrade: ^0.4.2 # 应用升级
  webview_flutter: ^4.8.0
  go_router: ^14.2.0
  sqflite: ^2.3.3+1 # 数据库
  sqflite_common_ffi: ^2.3.3 # 数据库
  shared_preferences: ^2.2.3 # xml 固化
  path_provider: ^2.1.3  # 路径

  dio: ^5.4.3+1 # 网络请求
  jwt_decoder: ^2.0.1 # jwt 解析
  connectivity_plus: ^6.0.3

  refresh: ^1.0.1
  toggle_rotate: ^1.0.1
  flutter_star: ^1.0.2 # 星星组件
  dash_painter: ^1.0.2
  wrapper: ^1.0.2

  url_launcher: ^6.3.0 # url
  share_plus: ^10.0.1 # 文字分享

  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  platform: ^3.1.0
  image: ^4.2.0
  flutter_spinkit: ^5.2.1 # loading
  flutter_markdown: ^0.7.2+1 # markdown
  file_picker: ^8.0.7
  l10n:
    path: packages/l10n
  utils:
    path: packages/utils
  storage:
    path: packages/storage
  widgets:
    path: packages/widgets
  draw_system:
    path: packages/draw_system
  artifact:
    path: packages/artifact
  algorithm:
    path: packages/algorithm
  authentication:
    path: packages/authentication
  app:
    path: packages/app
  app_update:
    path: packages/app_update
  components:
    path: packages/components
  toly_ui:
    path: packages/toly_ui
  widget_module:
    path: packages/widget_module
  treasure_tools:
    path: packages/treasure_tools
  layout:
    path: packages/layout

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  fx_boot_starter:
    path: modules/fx_boot_starter
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/data/web/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF

toly:
  icon:
    src_zip: ''
    assets_dir: 'assets/iconfont'
    file_dist: 'packages/app/lib/app/res/toly_icon.dart'











