name: flutter_unit
description: A new Flutter application.
publish_to: none
version: 3.0.0
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  ## fx 架构
  fx_boot_starter: 0.0.1 # app 启动器
  go_router: ^14.2.0

  flutter_bloc: ^8.1.6 # 状态管理
  equatable: ^2.0.5 # 相等辅助

  shared_preferences: ^2.2.2 # xml 固化
  connectivity_plus: ^6.0.3

  # tolyui
  tolyui: ^0.0.2+15

  l10n:
    path: modules/basic_system/l10n
  app:
    path: modules/basic_system/app
  utils:
    path:  modules/basic_system/utils
  authentication:
    path: modules/basic_system/authentication
  components:
    path: modules/basic_system/components
  toly_ui:
    path: modules/basic_system/toly_ui
  storage:
    path:  modules/basic_system/storage
  app_update:
    path: modules/basic_system/app_update
  widgets:
    path:  modules/widget_system/widgets
  draw_system:
    path: modules/painting_system/draw_system
  artifact:
    path: modules/knowledge_system/artifact
  algorithm:
    path: modules/knowledge_system/algorithm
  widget_module:
    path: modules/widget_system/widget_module
  treasure_tools:
    path: modules/tools_system/treasure_tools
  layout:
    path: modules/knowledge_system/layout

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/data/web/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF

toly:
  icon:
    src_zip: ''
    assets_dir: 'assets/iconfont'
    file_dist: 'packages/app/lib/app/res/toly_icon.dart'











