arb-dir: lib/arb
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart


synthetic-package: false
output-dir: lib/gen_l10n
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: desiredFileName.txt